#CFLAGS += -Werror -Wall -O2 -g -fsanitize=address
CFLAGS += -Werror -Wall -O2 -g -ggdb3
NOCFLAGS := $(CFLAGS) -fgnu89-inline
NOCFLAGS += -DNOLIBNETMAP -DLIBNETMAP_NOTHREADSAFE

LDFLAGS += -lpthread -lm
LDFLAGS += -lbsd
CC = gcc
NOLDFLAGS := $(LDFLAGS) $(LIBS)
SPATH ?= -I../../sys/ -I../include -I../../libnetmap -DNETMAP_WITH_LIBS

PROG = phttpd

nophttpd: phttpd.c nmlib.h reflex.c
	$(CC) $(NOCFLAGS) $(SPATH) phttpd.c reflex.c -o nophttpd $(NOLDFLAGS)

clean:
	-@rm -f $(PROG)
